<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />  
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- 包含 bootstrap 样式表 -->
		<script src="js/jquery-1.11.1.min.js"></script>
		<link rel="stylesheet"
			href="css/bootstrap.min.css">
		<link rel="stylesheet"
			href="css/bootstrap-datetimepicker.min.css"
			media="screen">
		<link rel="stylesheet"
			href="css/hlwxx.css">
		<script type="text/javascript"
			src="js/bootstrap.min.js" charset="UTF-8"></script>
        <title>互联网信息</title>
    </head>
    <body>
		<div class="footer">
			<p class="copyright">互联网信息 © 2015 All rights reserved</p>
		</div>
 </body>
</html>

