<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />  
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- 包含 bootstrap 样式表 -->
		<script src="js/jquery-1.11.1.min.js"></script>
		<link rel="stylesheet"
			href="css/bootstrap.min.css">
		<link rel="stylesheet"
			href="css/bootstrap-datetimepicker.min.css"
			media="screen">
		<link rel="stylesheet"
			href="css/hlwxx.css">
		<script type="text/javascript"
			src="js/bootstrap.min.js" charset="UTF-8"></script>
        <title>互联网信息</title>
    </head>
    <body>
        <div class="top">
        	<br>
			<nav class="navbar navbar-default navbar-fixed-top">
	        <div class="container">
		        <div class="navbar-header">
		          <!-- The mobile navbar-toggle button can be safely removed since you do not need it in a non-responsive implementation -->
		          <a class="navbar-brand" href="#">互联网信息</a>
		        </div>
		        <!-- Note that the .navbar-collapse and .collapse classes have been removed from the #navbar -->
		        <div id="navbar">
		          <ul class="nav navbar-nav">
		            <li class="active"><a href="#">首页</a></li>
		            <li><a href="#history">往期</a></li>
		            <li><a href="#about">关于我们</a></li>
		            <li><a href="#contact">联系我们</a></li>
<!-- 		            <li class="dropdown"> -->
<!-- 		              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">最近几期<span class="caret"></span></a> -->
<!-- 		              <ul class="dropdown-menu"> -->
<!-- 		                <li><a href="#">最近一期</a></li> -->
<!-- 		                <li><a href="#">最近二期</a></li> -->
<!-- 		                <li><a href="#">最近三期</a></li> -->
<!-- 		                <li role="separator" class="divider"></li> -->
<!-- 		                <li class="dropdown-header"></li> -->
<!-- 		                <li><a href="#"></a></li> -->
<!-- 		              </ul> -->
<!-- 		            </li> -->
		          </ul>
		          <form class="navbar-form navbar-right" role="search">
		           	电子邮件：
		            <div class="form-group">
		              <input type="text" class="form-control" placeholder="请输入邮箱地址...">
		            </div>
		            <button type="submit" class="btn btn-primary active">立刻订阅</button>
		          </form>
<!-- 		          <ul class="nav navbar-nav navbar-right"> -->
<!-- 		            <li><a href="#"></a></li> -->
<!-- 		            <li><a href="#"></a></li> -->
<!-- 		            <li><a href="#"></a></li> -->
<!-- 		          </ul> -->
		        </div><!--/.nav-collapse -->
		      </div>
		    </nav>
	    </div>
    <!-- end top -->
    
    
    </body>
</html>

