<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- 包含 bootstrap 样式表 -->
		<script src="js/jquery-1.11.1.min.js"></script>
		<link rel="stylesheet"
			href="css/bootstrap.min.css">
		<link rel="stylesheet"
			href="css/bootstrap-datetimepicker.min.css"
			media="screen">
		<link rel="stylesheet"
			href="css/hlwxx.css">
		<script type="text/javascript"
			src="js/bootstrap.min.js" charset="UTF-8"></script>
        <title>互联网信息</title>
    </head>
    
    <body>
  
      <div class="page-header">
        <h1>互联网信息技术周刊</h1>
        <p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;互联网信息技术周刊是由一群从事互联网技术的一线资深工程师组成的技术精选分享周刊。<strong>分享的都是精品。</strong></p>
      </div>

    </body>
</html>